;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ability.Event.Vehicle.Unmount",NewTagName="Ability.Event.ExitVehicle")
+GameplayTagRedirects=(OldTagName="Damage.Type.Physical",NewTagName="GameplayEffect.DamageType.Physical")
+GameplayTagRedirects=(OldTagName="Ability.Event.ExitVehicle",NewTagName="GameplayEvent.ExitVehicle")
+GameplayTagRedirects=(OldTagName="Ability.Event.Test",NewTagName="GameplayEvent.Test")
+GameplayTagRedirects=(OldTagName="InputTag.Vehicle.RowDirectionLeft",NewTagName="InputTag.Vehicle.RowHarder")
+GameplayTagRedirects=(OldTagName="GameplayEffect.DamageType",NewTagName="GameplayEffect.Damage.DamageType")
+GameplayTagRedirects=(OldTagName="GameplayEffect.DamageType.Physical",NewTagName="GameplayEffect.Damage.DamageType.Physical")
+GameplayTagRedirects=(OldTagName="Character.State.Interacting",NewTagName="GameplayEffect.Interacting")
+GameplayTagRedirects=(OldTagName="GameplayEffect.Interacting",NewTagName="Status.Character.Interacting")
+GameplayTagRedirects=(OldTagName="Character.State.Riding",NewTagName="Status.Character.RidingVehicle")
+GameplayTagRedirects=(OldTagName="Vehicle.Ability.BoatJump.Cooldwon",NewTagName="Ability.BoatJump.Cooldown")
+GameplayTagRedirects=(OldTagName="Vehicle.Rider.Holdfast",NewTagName="Status.Character.HoldingVehicle")
+GameplayTagList=(Tag="Ability.BoatJump.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Death.Message",DevComment="")
+GameplayTagList=(Tag="Ability.EnterVehicle.Message",DevComment="베히클 탑승 성공 시 보낼 메시지")
+GameplayTagList=(Tag="Ability.Interaction.Prompt.Message",DevComment="")
+GameplayTagList=(Tag="Ability.Row.Cooldown",DevComment="")
+GameplayTagList=(Tag="Ability.Row.Message",DevComment="")
+GameplayTagList=(Tag="Ability.Row.TestMessage",DevComment="나중에지워")
+GameplayTagList=(Tag="Action.Type.RiderBasic",DevComment="라이더 어빌리티 기본 타입")
+GameplayTagList=(Tag="Action.Type.RideVehicle",DevComment="베히클 탑승 관련 어빌리티 타입")
+GameplayTagList=(Tag="Action.Type.TestA",DevComment="")
+GameplayTagList=(Tag="Action.Type.TestB",DevComment="")
+GameplayTagList=(Tag="AnimNotify.Test",DevComment="")
+GameplayTagList=(Tag="Character.State.UsingHands.Left",DevComment="")
+GameplayTagList=(Tag="Character.State.UsingHands.Right",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Impact.Wood",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Test2",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Damage.DamageType",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Damage.DamageType.Physical",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.TestEffect",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.BoatJump",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Death",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.ExitVehicle",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Test",DevComment="")
+GameplayTagList=(Tag="InputTag.Cancel",DevComment="")
+GameplayTagList=(Tag="InputTag.Confirm",DevComment="")
+GameplayTagList=(Tag="InputTag.Interaction",DevComment="")
+GameplayTagList=(Tag="InputTag.Jump",DevComment="")
+GameplayTagList=(Tag="InputTag.Sprint",DevComment="")
+GameplayTagList=(Tag="InputTag.Test.TestAction2",DevComment="")
+GameplayTagList=(Tag="InputTag.TestAbility",DevComment="")
+GameplayTagList=(Tag="InputTag.Vehicle.Action1",DevComment="")
+GameplayTagList=(Tag="InputTag.Vehicle.Action2",DevComment="")
+GameplayTagList=(Tag="InputTag.Vehicle.Action3",DevComment="")
+GameplayTagList=(Tag="InputTag.Vehicle.Action4",DevComment="")
+GameplayTagList=(Tag="InputTag.Vehicle.Action5",DevComment="")
+GameplayTagList=(Tag="InputTag.Vehicle.RowBackward",DevComment="")
+GameplayTagList=(Tag="InputTag.Vehicle.RowHarder",DevComment="")
+GameplayTagList=(Tag="InputTag.WASDBack",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Damage",DevComment="")
+GameplayTagList=(Tag="SetByCaller.RunSpeed",DevComment="")
+GameplayTagList=(Tag="Status.Character.HoldingVehicle",DevComment="")
+GameplayTagList=(Tag="Status.Character.Interacting",DevComment="")
+GameplayTagList=(Tag="Status.Character.Interrupted",DevComment="약한 CC")
+GameplayTagList=(Tag="Status.Character.RidingVehicle",DevComment="")
+GameplayTagList=(Tag="Status.Character.Stunned",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="")

