#pragma once

#include "NativeGameplayTags.h"

namespace CharonGameplayTags
{
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Test);
	
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Ability_Event_Interaction);

	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Ability_Option_RemoveOnEnd);
}