#pragma once

#include "NativeGameplayTags.h"

namespace CharonGameplayTags
{
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Test);
	
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Interaction);

	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Option_RemoveOnEnd);
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Option_IgnoreDeath);
	PROJECTCHARON_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_Option_IgnoreDeath);
}